### ISSUE TITLE
Checking connection: FAILED

### ISSUE THREAD

**Issue by jphager2** [railsrumble/r15-team-292#2]
dblink always seems to fail when checking the connection.

I get the various urls output, but cannot connect.

```
Checking connection to localhost:5432 - OK
Creating configs in /tmp folder - OK
Starting pgbouncer - OK (pid: 70935)
Starting SSH tonnel - OK (pid: 70936)
Remote port: 43557
Checking connection: FAILED

psql: could not connect to server: Operation timed out
	Is the server running on host "dblink.tk" (46.101.192.49) and accepting
	TCP/IP connections on port 43557?
```

love the idea of dblink, and looking forward to getting it to work

**Comment by Paxa** [comment]
Thank you for your feedback

Seems like pgbouncer can not start

What is your operating system?
Try run with -v argument, it will give you debug info. Or try to disable
connection checking. (Run with '--help' to see all options)

**Comment by jphager2** [comment]
I guess I wasn't patient enough. It started working when I went home. Maybe a network issue in the office =).
